name: Mundial2026API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar paquetes
        run: dotnet restore

      - name: Compilar solución
        run: dotnet build --no-restore

      - name: Ejecutar tests
        run: dotnet test --no-build --verbosity normal